import { jsonSchema } from '@/lib/utils/validation-schemas';
import { ColumnSchema, ColumnType } from '@insforge/shared-schemas';
import { z } from 'zod';

// Helper function to check if a field should be auto-generated
export function isAutoGeneratedField(field: ColumnSchema): boolean {
  // Always hide the ID field - users shouldn't input ID values
  if (field.isPrimaryKey && field.columnName === 'id') {
    return true;
  }

  // Check for UUID pattern in default value
  if (field.defaultValue && typeof field.defaultValue === 'string') {
    // SQLite UUID generation pattern
    if (field.defaultValue.includes('randomblob') || field.defaultValue.includes('hex')) {
      return true;
    }

    // Only hide CURRENT_TIMESTAMP fields if they are isNullable (auto-managed)
    // Non-isNullable datetime fields should be shown so users can set specific values
    if (
      field.defaultValue.toUpperCase().includes('CURRENT_TIMESTAMP') ||
      field.defaultValue.endsWith('()')
    ) {
      // Hide auto-managed timestamp fields (created_at, updated_at) - these are typically isNullable and auto-managed
      if (field.columnName === 'created_at' || field.columnName === 'updated_at') {
        return true;
      }
      // Show non-isNullable datetime fields even if they have CURRENT_TIMESTAMP default
      // Users might want to set a specific datetime instead of using the default
      return false;
    }
  }

  return false;
}

// Helper function to build dynamic Zod schema based on column definitions
export function buildDynamicSchema(columns: ColumnSchema[]) {
  const schemaFields: Record<string, any> = {};

  columns.forEach((column) => {
    // Skip auto-generated fields
    if (isAutoGeneratedField(column)) {
      return;
    }

    let fieldSchema;

    switch (column.type) {
      case ColumnType.STRING:
        fieldSchema = z.string();
        if (!column.isNullable) {
          fieldSchema = fieldSchema.min(1, `${column.columnName} is required`);
        }
        break;
      case ColumnType.INTEGER:
        fieldSchema = z.number().int();
        if (column.isNullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
        break;
      case ColumnType.FLOAT:
        fieldSchema = z.number();
        if (column.isNullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
        break;
      case ColumnType.BOOLEAN:
        fieldSchema = z.boolean();
        if (column.isNullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
        break;
      case ColumnType.DATETIME:
        fieldSchema = z.string(); // ISO date string
        if (column.isNullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
        break;
      case ColumnType.JSON:
        fieldSchema = jsonSchema;
        if (column.isNullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
        break;
      default:
        fieldSchema = z.any();
        if (column.isNullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
    }

    schemaFields[column.columnName] = fieldSchema;
  });

  return z.object(schemaFields);
}

// Get initial values for form based on column definitions
export function getInitialValues(columns: ColumnSchema[]): Record<string, any> {
  const values: Record<string, any> = {};

  columns.forEach((column) => {
    // Skip auto-generated fields
    if (isAutoGeneratedField(column)) {
      return;
    }

    // Set default values based on type and defaultValue setting
    switch (column.type) {
      case ColumnType.BOOLEAN:
        if (column.defaultValue !== undefined && column.defaultValue !== null) {
          values[column.columnName] = column.defaultValue === 'true';
        }
        break;
      case ColumnType.INTEGER:
        if (column.defaultValue !== undefined) {
          values[column.columnName] = parseInt(column.defaultValue, 10);
        }
        break;
      case ColumnType.FLOAT:
        if (column.defaultValue !== undefined) {
          values[column.columnName] = parseFloat(column.defaultValue);
        }
        break;
      case ColumnType.STRING:
        values[column.columnName] = column.defaultValue ?? '';
        break;
      case ColumnType.UUID:
        if (column.defaultValue && !column.defaultValue.endsWith('()')) {
          // Static UUID default value
          values[column.columnName] = column.defaultValue;
        } else {
          // For gen_random_uuid() or no default, leave empty - will be generated on submit
          values[column.columnName] = '';
        }
        break;
      case ColumnType.DATETIME:
        if (column.defaultValue && !column.defaultValue.endsWith('()')) {
          values[column.columnName] = new Date(column.defaultValue).toISOString();
        } else {
          values[column.columnName] = '';
        }
        break;
      case ColumnType.JSON:
        values[column.columnName] = column.defaultValue ?? '';
        break;
      default:
        values[column.columnName] = '';
    }
  });

  return values;
}
