import { z } from 'zod';
import { ColumnSchema } from '@/features/database/schema';

// Helper function to check if a field should be auto-generated
export function isAutoGeneratedField(field: ColumnSchema): boolean {
  // Don't hide the ID field - it should be shown with optional input
  if (field.primary_key && field.name === 'id') {
    return false;
  }

  // Check for UUID pattern in default value
  if (field.default_value && typeof field.default_value === 'string') {
    // SQLite UUID generation pattern
    if (field.default_value.includes('randomblob') || field.default_value.includes('hex')) {
      return true;
    }

    // Only hide CURRENT_TIMESTAMP fields if they are nullable (auto-managed)
    // Non-nullable datetime fields should be shown so users can set specific values
    if (field.default_value.toUpperCase().includes('CURRENT_TIMESTAMP')) {
      // Hide auto-managed timestamp fields (created_at, updated_at) - these are typically nullable and auto-managed
      if (field.name === 'created_at' || field.name === 'updated_at') {
        return true;
      }
      // Show non-nullable datetime fields even if they have CURRENT_TIMESTAMP default
      // Users might want to set a specific datetime instead of using the default
      return false;
    }
  }

  return false;
}

// Helper function to build dynamic Zod schema based on column definitions
export function buildDynamicSchema(columns: ColumnSchema[]) {
  const schemaFields: Record<string, any> = {};

  columns.forEach((column) => {
    // Skip auto-generated fields
    if (isAutoGeneratedField(column)) {
      return;
    }

    let fieldSchema;

    // Special handling for ID field - always optional for creation
    if (column.name === 'id' && column.primary_key) {
      fieldSchema = z.string().optional();
      schemaFields[column.name] = fieldSchema;
      return;
    }

    switch (column.type) {
      case 'TEXT':
      case 'string':
        fieldSchema = z.string();
        if (!column.nullable) {
          fieldSchema = fieldSchema.min(1, `${column.name} is required`);
        }
        break;
      case 'INTEGER':
      case 'integer':
        fieldSchema = z.number().int();
        if (column.nullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
        break;
      case 'REAL':
      case 'float':
        fieldSchema = z.number();
        if (column.nullable) {
          fieldSchema = fieldSchema.nullable().optional();
        }
        break;
      case 'boolean':
        fieldSchema = z.boolean();
        if (column.nullable) {
          fieldSchema = fieldSchema.optional();
        }
        break;
      case 'datetime':
        fieldSchema = z.string(); // ISO date string
        if (column.nullable) {
          fieldSchema = fieldSchema.optional();
        }
        break;
      case 'json':
        fieldSchema = z.string(); // JSON string
        if (column.nullable) {
          fieldSchema = fieldSchema.optional();
        }
        break;
      default:
        fieldSchema = z.any();
        if (column.nullable) {
          fieldSchema = fieldSchema.optional();
        }
    }

    schemaFields[column.name] = fieldSchema;
  });

  return z.object(schemaFields);
}

// Get initial values for form based on column definitions
export function getInitialValues(columns: ColumnSchema[]): Record<string, any> {
  const values: Record<string, any> = {};

  columns.forEach((column) => {
    // Skip auto-generated fields
    if (isAutoGeneratedField(column)) {
      return;
    }

    // ID field should default to empty string (optional)
    if (column.name === 'id' && column.primary_key) {
      values[column.name] = '';
      return;
    }

    // Set default values based on type
    switch (column.type) {
      case 'boolean':
        values[column.name] = false;
        break;
      case 'INTEGER':
      case 'integer':
      case 'REAL':
      case 'float':
        values[column.name] = column.nullable ? undefined : 0;
        break;
      default:
        values[column.name] = '';
    }
  });

  return values;
}
